In [154]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [155]:
df = pd.read_csv('CustomerChurn-17205707.csv')
df

,customer,age,occupation,regionType,marriageStatus,children,income,numHandsets,handsetAge,smartPhone,...,avgInCalls,peakOffPeakRatio,peakOffPeakRatioChangePct,avgDroppedCalls,lifeTime,lastMonthCustomerCareCalls,numRetentionCalls,numRetentionOffersAccepted,newFrequentNumbers,churn
0,1093902,0,,suburban,unknown,false,0,2,34,true,...,10.33,1.328110,-16.834908,19.00,10,2.33,0,0,0,false
1,1050652,56,,suburban,unknown,false,6,2,468,true,...,1.33,2.504268,5.880220,11.33,19,2.33,0,0,0,true
2,1057527,0,,,unknown,false,0,1,332,true,...,25.67,0.842595,16.035861,7.00,11,3.67,0,0,0,true
3,1084529,0,,suburban,unknown,false,0,1,366,true,...,2.00,2.206985,7.113580,12.67,13,2.67,1,0,1,true
4,1032668,50,professional,,yes,false,6,1,733,true,...,0.00,1.445173,-10.457982,1.67,25,8.00,0,0,1,false
5,1086017,0,,,no,false,7,2,30,true,...,7.67,1.169293,-2.291091,3.67,6,1.00,0,0,0,false
6,1030370,24,student,town,no,false,1,3,315,true,...,5.33,3.058250,-3.406113,19.00,23,0.00,0,0,0,false
7,1079916,56,,suburban,yes,true,6,1,378,true,...,0.00,0.000000,-4.402007,0.00,13,0.00,0,0,0,false
8,1095902,42,,suburban,yes,true,6,1,233,true,...,5.00,0.695143,-19.142916,3.00,8,2.67,0,0,0,false
9,1056801,26,,,no,false,1,2,130,true,...,2.00,3.911343,1.832397,5.67,17,1.00,0,0,0,false
10,1042712,58,,,no,true,6,1,460,true,...,0.00,1.366500,-3.590748,4.67,15,0.67,0,0,0,false
11,1003081,38,,suburban,no,false,8,2,380,true,...,0.67,2.776915,-4.411496,7.67,42,0.00,0,0,0,false
12,1054954,0,,,unknown,false,0,2,182,true,...,0.67,1.129369,3.436160,2.67,16,0.67,0,0,0,false
13,1075715,26,,,no,false,4,1,288,true,...,2.67,1.079639,-22.636919,10.33,9,0.00,0,0,0,true
14,1082107,42,professional,suburban,unknown,true,9,1,311,true,...,0.00,2.914486,-17.080167,3.67,11,0.00,0,0,0,true
15,1098775,22,,suburban,no,false,7,1,1060,true,...,16.33,1.060636,-2.992962,6.33,35,0.00,1,0,0,false
16,1074500,42,,suburban,yes,false,4,2,215,true,...,0.67,1.642742,-8.786891,1.00,12,0.00,0,0,0,false
17,1028485,46,professional,,no,false,2,4,118,true,...,0.33,0.680411,3.670368,8.67,19,5.00,1,0,0,true
18,1018554,26,,,no,false,5,2,349,true,...,1.67,10.778443,8.788531,1.33,23,0.00,0,0,0,true
19,1040707,0,,,unknown,false,0,2,411,true,...,0.00,0.000000,-15.575882,0.00,22,0.00,0,0,0,true
20,1033121,50,,suburban,yes,false,9,1,731,true,...,1.67,1.293326,3.164516,0.33,25,0.67,0,0,0,true
21,1094948,36,,,unknown,true,3,1,195,true,...,20.67,1.436018,-3.039710,8.33,7,0.00,0,0,0,false
22,1025827,48,professional,suburban,no,true,7,3,130,true,...,14.00,0.806274,12.028089,8.33,26,0.00,0,0,3,false
23,1023986,34,,,unknown,false,9,7,102,true,...,4.33,0.897522,-10.314021,11.33,27,22.00,0,0,0,false
24,1029483,32,,,unknown,false,7,3,71,true,...,0.00,1.000000,16.575286,18.00,21,0.33,0,0,0,true
25,1047730,46,,suburban,unknown,false,8,2,263,true,...,12.33,0.931318,-8.780781,36.00,14,0.00,0,0,0,true
26,1021410,34,,suburban,unknown,false,7,1,830,true,...,17.00,3.710648,-10.372818,70.33,28,0.67,0,0,0,false
27,1053535,58,,,unknown,false,6,1,361,true,...,0.00,4.055292,-9.824126,1.33,12,0.67,0,0,0,false
28,1008901,36,clerical,suburban,unknown,false,6,3,645,false,...,0.00,2.592087,-24.867145,1.00,32,0.00,0,0,0,true
29,1074297,36,professional,,no,false,3,1,233,true,...,0.00,0.000000,-2.579869,0.00,8,0.00,0,0,0,false
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
970,1090213,0,,suburban,unknown,false,0,1,214,true,...,37.00,1.071223,-1.048943,61.00,7,11.00,0,0,0,true
971,1015120,42,,suburban,no,false,1,2,488,true,...,0.67,0.425058,-3.602671,11.33,27,0.00,0,0,0,false
972,1077896,24,,town,unknown,false,5,1,386,true,...,1.33,0.744654,-9.087884,5.33,13,0.00,0,0,0,true
973,1093205,64,,,yes,false,1,2,97,true,...,44.00,1.091076,3.465760,29.67,8,8.33,0,0,0,false
974,1041420,26,,suburban,yes,false,7,2,259,true,...,0.00,1.992715,9.752807,8.00,16,2.33,0,0,0,false
975,1081852,36,,town,yes,false,7,1,373,true,...,0.00,1.388333,-4.575006,1.33,13,0.00,0,0,0,true
976,1035407,46,professional,town,yes,false,5,1,536,false,...,0.00,10.090909,2.008861,0.00,18,0.33,0,0,0,false
977,1098370,36,,,yes,false,8,1,1158,false,...,0.00,2.714286,-14.451867,1.00,38,0.00,0,0,0,true
978,1074539,62,retired,suburban,no,false,3,2,44,true,...,4.33,2.330581,-3.970329,3.33,8,0.00,0,0,0,false
979,1035613,24,,,yes,false,6,1,534,true,...,17.33,0.507902,-2.099039,5.00,18,2.00,0,0,0,false
980,1070808,0,,,unknown,false,0,1,253,true,...,0.00,0.000000,-3.705888,0.00,8,0.00,0,0,0,true
981,1082319,54,,town,yes,false,5,1,372,true,...,5.33,7.708761,-2.124212,9.33,13,4.67,0,0,0,false
982,1050909,32,,rural,yes,false,6,1,553,true,...,12.33,4.355363,6.218734,5.33,19,0.33,0,0,0,true
983,1043887,36,,,no,true,6,6,10,true,...,21.67,2.084746,1.435801,16.33,19,3.00,0,0,1,true
984,1024572,38,,suburban,yes,false,8,2,91,true,...,15.33,1.848636,5.185700,6.33,20,3.33,0,0,0,false
985,1029758,0,,suburban,no,true,6,4,43,true,...,3.00,1.304018,-0.171826,45.67,25,11.67,0,0,0,false
986,1071351,0,,town,unknown,false,0,1,249,true,...,0.00,0.000000,2.200524,0.00,8,0.00,0,0,0,true
987,1075878,40,student,rural,yes,true,6,1,395,true,...,0.00,0.755841,11.481605,9.00,14,0.00,0,0,0,false
988,1075159,22,crafts,,no,false,4,1,337,true,...,44.00,4.296875,4.466428,14.00,12,0.00,0,0,0,true
989,1080522,0,,suburban,yes,false,3,1,315,true,...,13.00,0.729461,0.423527,6.00,11,0.00,0,0,0,false
990,1070825,38,,,yes,true,9,1,361,true,...,0.00,3.552648,15.100812,2.33,12,0.00,0,0,0,false
991,1027298,52,crafts,,yes,true,3,4,328,true,...,53.33,1.182430,4.418800,9.67,23,14.33,0,0,0,true
992,1024919,0,,,unknown,false,0,2,210,true,...,8.67,2.999559,2.210906,4.00,26,0.33,0,0,0,false
993,1080551,0,,suburban,unknown,false,0,3,147,true,...,0.00,3.577321,6.128173,1.67,13,13.33,0,0,0,false
994,1035460,0,,suburban,unknown,false,0,1,536,true,...,0.00,3.819918,-18.742702,5.00,18,0.00,0,0,0,false
995,1030143,60,professional,town,unknown,true,9,1,634,true,...,0.67,1.455662,-1.701951,1.67,21,0.00,0,0,0,true
996,1042759,28,,,no,false,5,2,335,true,...,8.67,2.013889,19.430173,9.00,19,3.33,0,0,0,false
997,1029266,38,,rural,yes,false,6,2,584,true,...,11.00,3.067288,-2.820711,3.67,25,0.00,0,0,0,true
998,1004780,34,,suburban,yes,false,7,3,4,false,...,0.00,2.247191,-22.669255,0.33,33,0.00,0,0,0,false
999,1031250,52,,,no,true,9,2,387,true,...,2.33,1.399747,8.356701,10.00,21,0.00,0,0,0,true

In [156]:
df.shape

(1000, 33)

In [157]:
df.head(6)

,customer,age,occupation,regionType,marriageStatus,children,income,numHandsets,handsetAge,smartPhone,...,avgInCalls,peakOffPeakRatio,peakOffPeakRatioChangePct,avgDroppedCalls,lifeTime,lastMonthCustomerCareCalls,numRetentionCalls,numRetentionOffersAccepted,newFrequentNumbers,churn
0,1093902,0,,suburban,unknown,false,0,2,34,true,...,10.33,1.328110,-16.834908,19.00,10,2.33,0,0,0,false
1,1050652,56,,suburban,unknown,false,6,2,468,true,...,1.33,2.504268,5.880220,11.33,19,2.33,0,0,0,true
2,1057527,0,,,unknown,false,0,1,332,true,...,25.67,0.842595,16.035861,7.00,11,3.67,0,0,0,true
3,1084529,0,,suburban,unknown,false,0,1,366,true,...,2.00,2.206985,7.113580,12.67,13,2.67,1,0,1,true
4,1032668,50,professional,,yes,false,6,1,733,true,...,0.00,1.445173,-10.457982,1.67,25,8.00,0,0,1,false
5,1086017,0,,,no,false,7,2,30,true,...,7.67,1.169293,-2.291091,3.67,6,1.00,0,0,0,false

In [158]:
df.dtypes

customer                        int64
 age                            int64
 occupation                    object
 regionType                    object
marriageStatus                 object
 children                      object
 income                         int64
numHandsets                     int64
handsetAge                      int64
smartPhone                     object
currentHandsetPrice           float64
 creditRating                  object
homeOwner                      object
 creditCard                    object
avgBill                       float64
avgMins                       float64
avgrecurringCharge            float64
avgOverBundleMins             float64
avgRoamCalls                  float64
callMinutesChangePct          float64
billAmountChangePct           float64
avgReceivedMins               float64
avgOutCalls                   float64
avgInCalls                    float64
peakOffPeakRatio              float64
peakOffPeakRatioChangePct     float64
avgDroppedCalls               float64
lifeTime                        int64
lastMonthCustomerCareCalls    float64
numRetentionCalls               int64
numRetentionOffersAccepted      int64
newFrequentNumbers              int64
churn                          object
dtype: object

In [159]:
df.describe()

,customer,age,income,numHandsets,handsetAge,currentHandsetPrice,avgBill,avgMins,avgrecurringCharge,avgOverBundleMins,...,avgOutCalls,avgInCalls,peakOffPeakRatio,peakOffPeakRatioChangePct,avgDroppedCalls,lifeTime,lastMonthCustomerCareCalls,numRetentionCalls,numRetentionOffersAccepted,newFrequentNumbers
count,1.000000e+03,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.00000,1000.000000,1000.000000,1000.000000,...,1000.000000,1000.00000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.00000,1000.000000
mean,1.050598e+06,29.696000,4.239000,1.762000,384.024000,34.305820,61.00849,535.594410,47.843010,45.700170,...,25.331940,8.51119,2.316633,-0.297586,10.279870,18.476000,1.931210,0.047000,0.02000,0.216000
std,2.852174e+04,22.464288,3.138747,1.339085,250.924284,55.652689,48.12100,565.981024,25.913972,113.103302,...,35.030275,17.52564,4.139049,10.378566,16.012875,9.190315,6.642481,0.220997,0.14007,0.667675
min,1.000063e+06,0.000000,0.000000,1.000000,4.000000,0.000000,0.00000,0.000000,0.000000,0.000000,...,0.000000,0.00000,0.000000,-35.792105,0.000000,6.000000,0.000000,0.000000,0.00000,0.000000
25%,1.026606e+06,0.000000,0.000000,1.000000,205.000000,0.000000,33.69750,161.187500,30.000000,0.000000,...,3.670000,0.00000,0.781361,-7.091764,1.670000,11.000000,0.000000,0.000000,0.00000,0.000000
50%,1.050012e+06,34.000000,5.000000,1.000000,337.000000,0.000000,50.04500,363.250000,44.990000,4.125000,...,13.670000,1.67000,1.397686,-0.094406,5.330000,16.000000,0.000000,0.000000,0.00000,0.000000
75%,1.075746e+06,48.000000,7.000000,2.000000,518.750000,39.990000,71.64750,713.812500,59.990000,47.312500,...,33.000000,9.00000,2.499572,6.399000,12.670000,24.000000,1.670000,0.000000,0.00000,0.000000
max,1.099939e+06,84.000000,9.000000,15.000000,1476.000000,399.990000,469.67000,4598.750000,301.980000,1389.000000,...,328.000000,164.00000,77.787879,35.450534,194.670000,52.000000,172.330000,2.000000,1.00000,3.000000

In [160]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
customer,1000.0,1.050598e+06,28521.739996,1.000063e+06,1.026606e+06,1.050012e+06,1.075746e+06,1.099939e+06
age,1000.0,2.969600e+01,22.464288,0.000000e+00,0.000000e+00,3.400000e+01,4.800000e+01,8.400000e+01
income,1000.0,4.239000e+00,3.138747,0.000000e+00,0.000000e+00,5.000000e+00,7.000000e+00,9.000000e+00
numHandsets,1000.0,1.762000e+00,1.339085,1.000000e+00,1.000000e+00,1.000000e+00,2.000000e+00,1.500000e+01
handsetAge,1000.0,3.840240e+02,250.924284,4.000000e+00,2.050000e+02,3.370000e+02,5.187500e+02,1.476000e+03
currentHandsetPrice,1000.0,3.430582e+01,55.652689,0.000000e+00,0.000000e+00,0.000000e+00,3.999000e+01,3.999900e+02
avgBill,1000.0,6.100849e+01,48.121000,0.000000e+00,3.369750e+01,5.004500e+01,7.164750e+01,4.696700e+02
avgMins,1000.0,5.355944e+02,565.981024,0.000000e+00,1.611875e+02,3.632500e+02,7.138125e+02,4.598750e+03
avgrecurringCharge,1000.0,4.784301e+01,25.913972,0.000000e+00,3.000000e+01,4.499000e+01,5.999000e+01,3.019800e+02
avgOverBundleMins,1000.0,4.570017e+01,113.103302,0.000000e+00,0.000000e+00,4.125000e+00,4.731250e+01,1.389000e+03
avgRoamCalls,1000.0,1.223530e+00,5.252052,0.000000e+00,0.000000e+00,0.000000e+00,3.200000e-01,9.630000e+01
callMinutesChangePct,1000.0,-3.217548e-01,6.033818,-5.035500e+01,-1.577500e+00,-2.500000e-02,1.481250e+00,5.042500e+01
billAmountChangePct,1000.0,-1.495240e-02,0.934358,-5.688400e+00,-1.431500e-01,-5.000000e-03,6.410000e-02,1.019500e+01
avgReceivedMins,1000.0,1.209735e+02,182.778995,0.000000e+00,8.140000e+00,5.682000e+01,1.540725e+02,1.686920e+03
avgOutCalls,1000.0,2.533194e+01,35.030275,0.000000e+00,3.670000e+00,1.367000e+01,3.300000e+01,3.280000e+02
avgInCalls,1000.0,8.511190e+00,17.525640,0.000000e+00,0.000000e+00,1.670000e+00,9.000000e+00,1.640000e+02
peakOffPeakRatio,1000.0,2.316633e+00,4.139049,0.000000e+00,7.813612e-01,1.397686e+00,2.499572e+00,7.778788e+01
peakOffPeakRatioChangePct,1000.0,-2.975855e-01,10.378566,-3.579211e+01,-7.091764e+00,-9.440592e-02,6.399000e+00,3.545053e+01
avgDroppedCalls,1000.0,1.027987e+01,16.012875,0.000000e+00,1.670000e+00,5.330000e+00,1.267000e+01,1.946700e+02
lifeTime,1000.0,1.847600e+01,9.190315,6.000000e+00,1.100000e+01,1.600000e+01,2.400000e+01,5.200000e+01
lastMonthCustomerCareCalls,1000.0,1.931210e+00,6.642481,0.000000e+00,0.000000e+00,0.000000e+00,1.670000e+00,1.723300e+02
numRetentionCalls,1000.0,4.700000e-02,0.220997,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.000000e+00
numRetentionOffersAccepted,1000.0,2.000000e-02,0.140070,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
newFrequentNumbers,1000.0,2.160000e-01,0.667675,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,3.000000e+00

In [161]:
numericColumns = df.select_dtypes(['int64', 'float64']).columns
numericColumns

Index(['customer', ' age', ' income', 'numHandsets', 'handsetAge',
       'currentHandsetPrice', 'avgBill', 'avgMins', 'avgrecurringCharge',
       'avgOverBundleMins', 'avgRoamCalls', 'callMinutesChangePct',
       'billAmountChangePct', 'avgReceivedMins', 'avgOutCalls', 'avgInCalls',
       'peakOffPeakRatio', 'peakOffPeakRatioChangePct', 'avgDroppedCalls',
       'lifeTime', 'lastMonthCustomerCareCalls', 'numRetentionCalls',
       'numRetentionOffersAccepted', 'newFrequentNumbers'],
      dtype='object')

In [162]:
stringColumns = df.select_dtypes(['object']).columns
stringColumns

Index([' occupation', ' regionType', 'marriageStatus', ' children',
       'smartPhone', ' creditRating', 'homeOwner', ' creditCard', 'churn'],
      dtype='object')

In [190]:
for column in stringColumns:
    df[column] = df[column].astype('category')
df.dtypes

KeyError: ' occupation'

In [164]:
len(df['customer'].unique())

1000

In [165]:
print('Feature, UniqueValues')
for column in numericColumns:
    print(column + ',' + str(len(df[column].unique())))

Feature, UniqueValues
customer,1000
 age,33
 income,10
numHandsets,11
handsetAge,583
currentHandsetPrice,13
avgBill,847
avgMins,883
avgrecurringCharge,243
avgOverBundleMins,350
avgRoamCalls,191
callMinutesChangePct,774
billAmountChangePct,755
avgReceivedMins,866
avgOutCalls,247
avgInCalls,143
peakOffPeakRatio,901
peakOffPeakRatioChangePct,1000
avgDroppedCalls,143
lifeTime,44
lastMonthCustomerCareCalls,58
numRetentionCalls,3
numRetentionOffersAccepted,2
newFrequentNumbers,4

In [166]:
df.isnull().sum()

customer                      0
 age                          0
 occupation                   0
 regionType                   0
marriageStatus                0
 children                     0
 income                       0
numHandsets                   0
handsetAge                    0
smartPhone                    0
currentHandsetPrice           0
 creditRating                 0
homeOwner                     0
 creditCard                   0
avgBill                       0
avgMins                       0
avgrecurringCharge            0
avgOverBundleMins             0
avgRoamCalls                  0
callMinutesChangePct          0
billAmountChangePct           0
avgReceivedMins               0
avgOutCalls                   0
avgInCalls                    0
peakOffPeakRatio              0
peakOffPeakRatioChangePct     0
avgDroppedCalls               0
lifeTime                      0
lastMonthCustomerCareCalls    0
numRetentionCalls             0
numRetentionOffersAccepted    0
newFrequentNumbers            0
churn                         0
dtype: int64

In [167]:
df[numericColumns].isnull().sum()

customer                      0
 age                          0
 income                       0
numHandsets                   0
handsetAge                    0
currentHandsetPrice           0
avgBill                       0
avgMins                       0
avgrecurringCharge            0
avgOverBundleMins             0
avgRoamCalls                  0
callMinutesChangePct          0
billAmountChangePct           0
avgReceivedMins               0
avgOutCalls                   0
avgInCalls                    0
peakOffPeakRatio              0
peakOffPeakRatioChangePct     0
avgDroppedCalls               0
lifeTime                      0
lastMonthCustomerCareCalls    0
numRetentionCalls             0
numRetentionOffersAccepted    0
newFrequentNumbers            0
dtype: int64

In [168]:
df[stringColumns].isnull().sum()

 occupation       0
 regionType       0
marriageStatus    0
 children         0
smartPhone        0
 creditRating     0
homeOwner         0
 creditCard       0
churn             0
dtype: int64

In [169]:
df.describe()

,customer,age,income,numHandsets,handsetAge,currentHandsetPrice,avgBill,avgMins,avgrecurringCharge,avgOverBundleMins,...,avgOutCalls,avgInCalls,peakOffPeakRatio,peakOffPeakRatioChangePct,avgDroppedCalls,lifeTime,lastMonthCustomerCareCalls,numRetentionCalls,numRetentionOffersAccepted,newFrequentNumbers
count,1.000000e+03,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.00000,1000.000000,1000.000000,1000.000000,...,1000.000000,1000.00000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.00000,1000.000000
mean,1.050598e+06,29.696000,4.239000,1.762000,384.024000,34.305820,61.00849,535.594410,47.843010,45.700170,...,25.331940,8.51119,2.316633,-0.297586,10.279870,18.476000,1.931210,0.047000,0.02000,0.216000
std,2.852174e+04,22.464288,3.138747,1.339085,250.924284,55.652689,48.12100,565.981024,25.913972,113.103302,...,35.030275,17.52564,4.139049,10.378566,16.012875,9.190315,6.642481,0.220997,0.14007,0.667675
min,1.000063e+06,0.000000,0.000000,1.000000,4.000000,0.000000,0.00000,0.000000,0.000000,0.000000,...,0.000000,0.00000,0.000000,-35.792105,0.000000,6.000000,0.000000,0.000000,0.00000,0.000000
25%,1.026606e+06,0.000000,0.000000,1.000000,205.000000,0.000000,33.69750,161.187500,30.000000,0.000000,...,3.670000,0.00000,0.781361,-7.091764,1.670000,11.000000,0.000000,0.000000,0.00000,0.000000
50%,1.050012e+06,34.000000,5.000000,1.000000,337.000000,0.000000,50.04500,363.250000,44.990000,4.125000,...,13.670000,1.67000,1.397686,-0.094406,5.330000,16.000000,0.000000,0.000000,0.00000,0.000000
75%,1.075746e+06,48.000000,7.000000,2.000000,518.750000,39.990000,71.64750,713.812500,59.990000,47.312500,...,33.000000,9.00000,2.499572,6.399000,12.670000,24.000000,1.670000,0.000000,0.00000,0.000000
max,1.099939e+06,84.000000,9.000000,15.000000,1476.000000,399.990000,469.67000,4598.750000,301.980000,1389.000000,...,328.000000,164.00000,77.787879,35.450534,194.670000,52.000000,172.330000,2.000000,1.00000,3.000000

In [170]:
df.duplicated('customer')

0      False
1      False
2      False
3      False
4      False
5      False
6      False
7      False
8      False
9      False
10     False
11     False
12     False
13     False
14     False
15     False
16     False
17     False
18     False
19     False
20     False
21     False
22     False
23     False
24     False
25     False
26     False
27     False
28     False
29     False
       ...
970    False
971    False
972    False
973    False
974    False
975    False
976    False
977    False
978    False
979    False
980    False
981    False
982    False
983    False
984    False
985    False
986    False
987    False
988    False
989    False
990    False
991    False
992    False
993    False
994    False
995    False
996    False
997    False
998    False
999    False
Length: 1000, dtype: bool

In [171]:
columns = df.shape[0]
columns

1000

In [172]:
rows = df.shape[1]
rows

33

In [173]:
df.head(5)

,customer,age,occupation,regionType,marriageStatus,children,income,numHandsets,handsetAge,smartPhone,...,avgInCalls,peakOffPeakRatio,peakOffPeakRatioChangePct,avgDroppedCalls,lifeTime,lastMonthCustomerCareCalls,numRetentionCalls,numRetentionOffersAccepted,newFrequentNumbers,churn
0,1093902,0,,suburban,unknown,false,0,2,34,true,...,10.33,1.328110,-16.834908,19.00,10,2.33,0,0,0,false
1,1050652,56,,suburban,unknown,false,6,2,468,true,...,1.33,2.504268,5.880220,11.33,19,2.33,0,0,0,true
2,1057527,0,,,unknown,false,0,1,332,true,...,25.67,0.842595,16.035861,7.00,11,3.67,0,0,0,true
3,1084529,0,,suburban,unknown,false,0,1,366,true,...,2.00,2.206985,7.113580,12.67,13,2.67,1,0,1,true
4,1032668,50,professional,,yes,false,6,1,733,true,...,0.00,1.445173,-10.457982,1.67,25,8.00,0,0,1,false

In [174]:
df.tail(5)

,customer,age,occupation,regionType,marriageStatus,children,income,numHandsets,handsetAge,smartPhone,...,avgInCalls,peakOffPeakRatio,peakOffPeakRatioChangePct,avgDroppedCalls,lifeTime,lastMonthCustomerCareCalls,numRetentionCalls,numRetentionOffersAccepted,newFrequentNumbers,churn
995,1030143,60,professional,town,unknown,true,9,1,634,true,...,0.67,1.455662,-1.701951,1.67,21,0.00,0,0,0,true
996,1042759,28,,,no,false,5,2,335,true,...,8.67,2.013889,19.430173,9.00,19,3.33,0,0,0,false
997,1029266,38,,rural,yes,false,6,2,584,true,...,11.00,3.067288,-2.820711,3.67,25,0.00,0,0,0,true
998,1004780,34,,suburban,yes,false,7,3,4,false,...,0.00,2.247191,-22.669255,0.33,33,0.00,0,0,0,false
999,1031250,52,,,no,true,9,2,387,true,...,2.33,1.399747,8.356701,10.00,21,0.00,0,0,0,true

In [175]:
stringColumns = df.select_dtypes(['category']).columns
stringColumns

Index([' occupation', ' regionType', 'marriageStatus', ' children',
       'smartPhone', ' creditRating', 'homeOwner', ' creditCard', 'churn'],
      dtype='object')

In [186]:
## To remove whitespace from column names
df = df.rename(index=str, columns={' occupation' : 'occupation', ' regionType' : 'regionType',' marriageStatus': 'marriageStatus',' children' : 'children',' smartPhone':'smartPhone',' creditRating' : 'creditRating',' homeOwner' : 'homeOwner',' creditCard' : 'creditCard',' churn' : 'churn'})
df

,customer,age,occupation,regionType,marriageStatus,children,income,numHandsets,handsetAge,smartPhone,...,avgInCalls,peakOffPeakRatio,peakOffPeakRatioChangePct,avgDroppedCalls,lifeTime,lastMonthCustomerCareCalls,numRetentionCalls,numRetentionOffersAccepted,newFrequentNumbers,churn
0,1093902,0,,suburban,unknown,false,0,2,34,true,...,10.33,1.328110,-16.834908,19.00,10,2.33,0,0,0,false
1,1050652,56,,suburban,unknown,false,6,2,468,true,...,1.33,2.504268,5.880220,11.33,19,2.33,0,0,0,true
2,1057527,0,,,unknown,false,0,1,332,true,...,25.67,0.842595,16.035861,7.00,11,3.67,0,0,0,true
3,1084529,0,,suburban,unknown,false,0,1,366,true,...,2.00,2.206985,7.113580,12.67,13,2.67,1,0,1,true
4,1032668,50,professional,,yes,false,6,1,733,true,...,0.00,1.445173,-10.457982,1.67,25,8.00,0,0,1,false
5,1086017,0,,,no,false,7,2,30,true,...,7.67,1.169293,-2.291091,3.67,6,1.00,0,0,0,false
6,1030370,24,student,town,no,false,1,3,315,true,...,5.33,3.058250,-3.406113,19.00,23,0.00,0,0,0,false
7,1079916,56,,suburban,yes,true,6,1,378,true,...,0.00,0.000000,-4.402007,0.00,13,0.00,0,0,0,false
8,1095902,42,,suburban,yes,true,6,1,233,true,...,5.00,0.695143,-19.142916,3.00,8,2.67,0,0,0,false
9,1056801,26,,,no,false,1,2,130,true,...,2.00,3.911343,1.832397,5.67,17,1.00,0,0,0,false
10,1042712,58,,,no,true,6,1,460,true,...,0.00,1.366500,-3.590748,4.67,15,0.67,0,0,0,false
11,1003081,38,,suburban,no,false,8,2,380,true,...,0.67,2.776915,-4.411496,7.67,42,0.00,0,0,0,false
12,1054954,0,,,unknown,false,0,2,182,true,...,0.67,1.129369,3.436160,2.67,16,0.67,0,0,0,false
13,1075715,26,,,no,false,4,1,288,true,...,2.67,1.079639,-22.636919,10.33,9,0.00,0,0,0,true
14,1082107,42,professional,suburban,unknown,true,9,1,311,true,...,0.00,2.914486,-17.080167,3.67,11,0.00,0,0,0,true
15,1098775,22,,suburban,no,false,7,1,1060,true,...,16.33,1.060636,-2.992962,6.33,35,0.00,1,0,0,false
16,1074500,42,,suburban,yes,false,4,2,215,true,...,0.67,1.642742,-8.786891,1.00,12,0.00,0,0,0,false
17,1028485,46,professional,,no,false,2,4,118,true,...,0.33,0.680411,3.670368,8.67,19,5.00,1,0,0,true
18,1018554,26,,,no,false,5,2,349,true,...,1.67,10.778443,8.788531,1.33,23,0.00,0,0,0,true
19,1040707,0,,,unknown,false,0,2,411,true,...,0.00,0.000000,-15.575882,0.00,22,0.00,0,0,0,true
20,1033121,50,,suburban,yes,false,9,1,731,true,...,1.67,1.293326,3.164516,0.33,25,0.67,0,0,0,true
21,1094948,36,,,unknown,true,3,1,195,true,...,20.67,1.436018,-3.039710,8.33,7,0.00,0,0,0,false
22,1025827,48,professional,suburban,no,true,7,3,130,true,...,14.00,0.806274,12.028089,8.33,26,0.00,0,0,3,false
23,1023986,34,,,unknown,false,9,7,102,true,...,4.33,0.897522,-10.314021,11.33,27,22.00,0,0,0,false
24,1029483,32,,,unknown,false,7,3,71,true,...,0.00,1.000000,16.575286,18.00,21,0.33,0,0,0,true
25,1047730,46,,suburban,unknown,false,8,2,263,true,...,12.33,0.931318,-8.780781,36.00,14,0.00,0,0,0,true
26,1021410,34,,suburban,unknown,false,7,1,830,true,...,17.00,3.710648,-10.372818,70.33,28,0.67,0,0,0,false
27,1053535,58,,,unknown,false,6,1,361,true,...,0.00,4.055292,-9.824126,1.33,12,0.67,0,0,0,false
28,1008901,36,clerical,suburban,unknown,false,6,3,645,false,...,0.00,2.592087,-24.867145,1.00,32,0.00,0,0,0,true
29,1074297,36,professional,,no,false,3,1,233,true,...,0.00,0.000000,-2.579869,0.00,8,0.00,0,0,0,false
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
970,1090213,0,,suburban,unknown,false,0,1,214,true,...,37.00,1.071223,-1.048943,61.00,7,11.00,0,0,0,true
971,1015120,42,,suburban,no,false,1,2,488,true,...,0.67,0.425058,-3.602671,11.33,27,0.00,0,0,0,false
972,1077896,24,,town,unknown,false,5,1,386,true,...,1.33,0.744654,-9.087884,5.33,13,0.00,0,0,0,true
973,1093205,64,,,yes,false,1,2,97,true,...,44.00,1.091076,3.465760,29.67,8,8.33,0,0,0,false
974,1041420,26,,suburban,yes,false,7,2,259,true,...,0.00,1.992715,9.752807,8.00,16,2.33,0,0,0,false
975,1081852,36,,town,yes,false,7,1,373,true,...,0.00,1.388333,-4.575006,1.33,13,0.00,0,0,0,true
976,1035407,46,professional,town,yes,false,5,1,536,false,...,0.00,10.090909,2.008861,0.00,18,0.33,0,0,0,false
977,1098370,36,,,yes,false,8,1,1158,false,...,0.00,2.714286,-14.451867,1.00,38,0.00,0,0,0,true
978,1074539,62,retired,suburban,no,false,3,2,44,true,...,4.33,2.330581,-3.970329,3.33,8,0.00,0,0,0,false
979,1035613,24,,,yes,false,6,1,534,true,...,17.33,0.507902,-2.099039,5.00,18,2.00,0,0,0,false
980,1070808,0,,,unknown,false,0,1,253,true,...,0.00,0.000000,-3.705888,0.00,8,0.00,0,0,0,true
981,1082319,54,,town,yes,false,5,1,372,true,...,5.33,7.708761,-2.124212,9.33,13,4.67,0,0,0,false
982,1050909,32,,rural,yes,false,6,1,553,true,...,12.33,4.355363,6.218734,5.33,19,0.33,0,0,0,true
983,1043887,36,,,no,true,6,6,10,true,...,21.67,2.084746,1.435801,16.33,19,3.00,0,0,1,true
984,1024572,38,,suburban,yes,false,8,2,91,true,...,15.33,1.848636,5.185700,6.33,20,3.33,0,0,0,false
985,1029758,0,,suburban,no,true,6,4,43,true,...,3.00,1.304018,-0.171826,45.67,25,11.67,0,0,0,false
986,1071351,0,,town,unknown,false,0,1,249,true,...,0.00,0.000000,2.200524,0.00,8,0.00,0,0,0,true
987,1075878,40,student,rural,yes,true,6,1,395,true,...,0.00,0.755841,11.481605,9.00,14,0.00,0,0,0,false
988,1075159,22,crafts,,no,false,4,1,337,true,...,44.00,4.296875,4.466428,14.00,12,0.00,0,0,0,true
989,1080522,0,,suburban,yes,false,3,1,315,true,...,13.00,0.729461,0.423527,6.00,11,0.00,0,0,0,false
990,1070825,38,,,yes,true,9,1,361,true,...,0.00,3.552648,15.100812,2.33,12,0.00,0,0,0,false
991,1027298,52,crafts,,yes,true,3,4,328,true,...,53.33,1.182430,4.418800,9.67,23,14.33,0,0,0,true
992,1024919,0,,,unknown,false,0,2,210,true,...,8.67,2.999559,2.210906,4.00,26,0.33,0,0,0,false
993,1080551,0,,suburban,unknown,false,0,3,147,true,...,0.00,3.577321,6.128173,1.67,13,13.33,0,0,0,false
994,1035460,0,,suburban,unknown,false,0,1,536,true,...,0.00,3.819918,-18.742702,5.00,18,0.00,0,0,0,false
995,1030143,60,professional,town,unknown,true,9,1,634,true,...,0.67,1.455662,-1.701951,1.67,21,0.00,0,0,0,true
996,1042759,28,,,no,false,5,2,335,true,...,8.67,2.013889,19.430173,9.00,19,3.33,0,0,0,false
997,1029266,38,,rural,yes,false,6,2,584,true,...,11.00,3.067288,-2.820711,3.67,25,0.00,0,0,0,true
998,1004780,34,,suburban,yes,false,7,3,4,false,...,0.00,2.247191,-22.669255,0.33,33,0.00,0,0,0,false
999,1031250,52,,,no,true,9,2,387,true,...,2.33,1.399747,8.356701,10.00,21,0.00,0,0,0,true

In [189]:
df['object'].str.strip()

KeyError: 'object'

In [194]:
print('a', pd.unique(df.select_dtypes('category').columns.ravel()))

a ['occupation' 'regionType' 'marriageStatus' 'children' 'smartPhone'
 'creditRating' 'homeOwner' 'creditCard' 'churn']

In [193]:

stringColumns = df.select_dtypes(['category']).columns

stringColumns

Index(['occupation', 'regionType', 'marriageStatus', 'children', 'smartPhone',
       'creditRating', 'homeOwner', 'creditCard', 'churn'],
      dtype='object')

/Users/synq/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [226]:
df.columns = df.columns.str.strip()

In [246]:
df['occupation'].replace('', np.nan, inplace=True)
df.dropna(subset=['occupation'], inplace=True)

In [253]:
## Finding cardinality of attributes
print('Unique Occupations: ', pd.unique(df.occupation.str.strip().ravel()), '\n')
print('Unique Region Types: ', pd.unique(df.regionType.str.strip().ravel()), '\n')
print('Unique Marriage Status: ', pd.unique(df.marriageStatus.str.strip().ravel()), '\n')
print('Unique Children: ', pd.unique(df.children.str.strip().ravel()), '\n')
print('Unique Smart Phone: ', pd.unique(df.smartPhone.str.strip().ravel()), '\n')
print('Unique Credit Rating: ', pd.unique(df.creditRating.str.strip().ravel()), '\n')

Unique Occupations:  ['' 'professional' 'student' 'clerical' 'crafts' 'homemaker'
 'self-employed' 'retired']

Unique Region Types:  ['suburban' '' 'town' 'rural' 's' 'r' 'unknown' 't']

Unique Marriage Status:  ['unknown' 'yes' 'no']

Unique Children:  ['false' 'true']

Unique Smart Phone:  ['true' 'false']

Unique Credit Rating:  ['C' 'B' 'G' 'E' 'D' 'A' 'F']

In [254]:
df['regionType'] = df['regionType'].replace({'s': 'suburban', 'r': 'rural', 't': 'town'})
pd.unique(df['regionType'].str.strip().ravel())

array(['suburban', '', 'town', 'rural', 's', 'r', 'unknown', 't'], dtype=object)